apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/srujanreddya/helloworld-go:1.0
          env:
            - name: TARGET
              value: "Go Sample v1"
