name: Docker Image CI

on:
  push:
    branches: [ go-sample-application ]
  pull_request:
    branches: [ go-sample-application ]

jobs:

  build:

    runs-on: centos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag srujanreddya/helloworld-go:1.0
